### ISSUE TITLE
Could not find a valid gem 'sensu-plugins-graphite'

### ISSUE THREAD

**Issue by jcmartins** [sensu-plugins/sensu-plugins-graphite#1]
Hi, I have this message error when I run this:
/opt/sensu/embedded/bin/gem install sensu-plugins-graphite

ERROR:  Could not find a valid gem 'sensu-plugins-graphite' (>= 0) in any repository

tks
Joao

**Comment by mattyjones** [comment]
@jcmartins 
Not all of the repos have been created into gems yet.  The current list is [here](https://rubygems.org/search?utf8=%E2%9C%93&query=sensu-plugins).  Many of these can be built into gems if you would like though.

The current timeframe can be found [here](http://sensu-plugins.github.io/issue/2015/01/27/sensu-plugins-roadmap.html)

As developers get time to clean the code to ensure its uniform style, ensure dependencies are accounted for, and any other pain points an official gem will be created and released.  If you would like to help, fork the repo, and have at it, then submit a PR and we will be happy to look at it and push it to Rubygems if all is well.

Thanks.
