### ISSUE TITLE
Documentation should warn about performances of mutator-graphite

### ISSUE THREAD

**Issue by multani** [sensu-plugins/sensu-plugins-graphite#16]
I recently got lot of troubles on my Sensu servers because I was using a TCP socket handler to send metrics to Graphite and the `mutator-graphite` to reverse the name of my Sensu nodes (so they fit better into Graphite), and the mutator script was killing the performances of the machine, because the script was getting spawned each time metrics where being sent to Graphite and that's definitely not cheap.

See this thread on the sensu-users mailing-list: https://groups.google.com/forum/#!topic/sensu-users/1hkRSvL48ck

Would it be better to add a warning/note somewhere in the README or in the header of the script to warn about the performances implications?

**Comment by eheydrick** [comment]
I'd certainly take a PR with a docs update.
