### ISSUE TITLE
sensu 0.22.0 seems to have broken this plugin

### ISSUE THREAD

**Issue by shawnbutts** [sensu-plugins/sensu-plugins-graphite#25]
/opt/sensu/embedded/lib/ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'ipaddress' (= 0.8.0) - did find: [ipaddress-0.8.2] (Gem::LoadError)
Checked in 'GEM_PATH=/root/.gem/ruby/2.2.0:/opt/sensu/embedded/lib/ruby/gems/2.2.0', execute`gem env`for more information
        from /opt/sensu/embedded/lib/ruby/2.2.0/rubygems/specification.rb:1311:in`block in activate_dependencies'
        from /opt/sensu/embedded/lib/ruby/2.2.0/rubygems/specification.rb:1300:in `each'
        from /opt/sensu/embedded/lib/ruby/2.2.0/rubygems/specification.rb:1300:in`activate_dependencies'
        from /opt/sensu/embedded/lib/ruby/2.2.0/rubygems/specification.rb:1282:in `activate'
        from /opt/sensu/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:67:in`block in gem'
        from /opt/sensu/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:66:in `synchronize'
        from /opt/sensu/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:66:in`gem'
        from /opt/sensu/embedded/bin/check-graphite-data.rb:22:in `<main>'

**Comment by tarasbikhanov** [comment]
Any updates?

**Comment by sstarcher** [comment]
That's a problem installing the gem from the ruby repo.  I confirmed that the gem exists and installs.  Try your issue again, because the plugin is working for me in sensu 0.22.0 and 0.21.0

**Comment by tarasbikhanov** [comment]
Yes, it works after force update sensu and gem.
