### ISSUE TITLE
undefined method `unknown' in proxy.rb

### ISSUE THREAD

**Issue by darrylring** [sensu-plugins/sensu-plugins-graphite#28]
If a Graphite query returns no data, an undefined method exception is thrown instead of a message indicating no data was returned. The problem is on line 91 of proxy.rb (https://github.com/sensu-plugins/sensu-plugins-graphite/blob/master/lib/sensu-plugins-graphite/graphite_proxy/proxy.rb#L91).

Instead of `unknown`, this should just raise a `ProxyError`. The `run` method in the check itself should already call `unknown` if a `ProxyError` is caught (e.g. https://github.com/sensu-plugins/sensu-plugins-graphite/blob/master/bin/check-graphite-data.rb#L70)

**Comment by shpoont** [comment]
Still happens in 1.1.0

**Comment by majormoses** [comment]
@tmclaugh can you PR this, I'd love to get this fixed.

**Comment by tmclaugh** [comment]
I'm going to be honest here, I'm not sure why my change fixed this issue or even remember the problem.  I don't have an environment currently to test with either.  Can someone confirm that what I did really is the fix and why?  I don't want to submit a junk PR that I don't understand.

**Comment by darrylring** [comment]
I don't have access to the environment where I encountered this issue. The original issue is surely fixed, though, no? The `unknown` method is no longer called in `proxy.rb`.

**Comment by majormoses** [comment]
you are right, lets close this out and if anyone is able to replicate with latest (currently 2.2).

@tmclaugh the reason it fixed is is that by pulling in the base sensu check cli class that gave you access to `unknown` function.
