### ISSUE TITLE
Unknown tag 0.0.7

### ISSUE THREAD

**Issue by multani** [sensu-plugins/sensu-plugins-graphite#29]
[RubyGems.org has a 0.0.7 version of this plugin](https://rubygems.org/gems/sensu-plugins-graphite/versions/0.0.7) but the tag is not present in this repository :(

**Comment by obazoud** [comment]
+1

**Comment by cwjohnston** [comment]
Hello @multani and @obazoud, thanks for raising this issue. I've tagged 0.0.7 at d1ffa25bdd73b3bbe26a8a9a20d567f76c34b75f.
