### ISSUE TITLE
Gemspec specifies unresolvable dependency on `openssl`

### ISSUE THREAD

**Issue by cwjohnston** [sensu-plugins/sensu-plugins-graphite#3]
The gemspec for this repo [specifies a dependency on the openssl gem](https://github.com/sensu-plugins/sensu-plugins-graphite/blob/5987909e50aa83c790b05747cf629aecb9f89c4a/sensu-plugins-graphite.gemspec#L42), which has been [yanked from rubygems](https://rubygems.org/gems/openssl). 

I believe that the `require 'openssl'` statement is satisfied by the standard library in Ruby 1.9 and later, so this gem dependency should be unnecessary.

**Comment by tas50** [comment]
I removed the openssl dep from the gemspec

**Comment by jcustenborder** [comment]
Are you going to be pushing a new gem soon?

**Comment by mattyjones** [comment]
@jcustenborder done

**Comment by jcustenborder** [comment]
Thanks dude!
