### ISSUE TITLE
Default --from may cause issue with --age parameters

### ISSUE THREAD

**Issue by ROunofF** [sensu-plugins/sensu-plugins-graphite#31]
I was trying to build a check with this command:
    check-graphite-data.rb -a 90000 -t metric.slow_update -s localhost

The issue is that this metric collect only 1 datapoints per day. This was coming down a request on graphite like this
    GET /render?format=json&target=metric.slow_update&from=-10mins

Now this throws error as the datapoint are finally empty... This was hitting the condition https://github.com/sensu-plugins/sensu-plugins-graphite/blob/master/bin/check-graphite-data.rb#L123

I was able to workaround this by adding --from -2days however probably the -a could be check so that the default from is at least as big ?

**Comment by majormoses** [comment]
Defaults are just that and meant to be overwritten. That being said it sounds like there is something we can do to enhance this maybe bby printing out a message for the user for this condition. If you are willing I would take a sane PR for this.

**Comment by ROunofF** [comment]
I'm mixed on this PR #43 now make this an error message at least (It was a stack trace) : "CheckGraphiteData UNKNOWN: No data for time period and/or target". 

Logically tough, there is no reason to fetch more (or less) data than --age. So we could make config[:from] default to the same as :allowed_graphite_age in this check? However, in order to do that we would have to parse the config[:from] since it takes an "unit".

If you think, it should be done let me know, I'll do this and submit a PR. However the current state is probably clean enough to close this...

(Funnily the day you reply to this, is the day this check goes RED in my dashboard and reminds me that it was doing its jobs correctly ;))

**Comment by majormoses** [comment]
Not sure that's possible from what I remember options are immutable, once cast cannot be modified.

**Comment by ROunofF** [comment]
Let's close this then :)
