### ISSUE TITLE
Missing metrics

### ISSUE THREAD

**Issue by mendicm** [sensu-plugins/sensu-plugins-graphite#48]
Hello, I don't know if this is the good place for this question because I don't have at this moment any clue of this issue...
After I increased the number of connected clients sending metrics I'm getting this kind of graphs:
<img width="1419" alt="captura de pantalla 2017-03-17 a las 18 26 25" src="https://cloud.githubusercontent.com/assets/4120546/24055327/df5d22fe-0b3f-11e7-975f-49058e83d065.png">
There is something throttling the data flow but I don't know where.
My configuration is: sensu-redis-graphite-grafana. Redis is used for the transport too.
The cpu and ram on the server is ok, disk write speed is normal (up to 3MB/s). Not found errors on sensu clients/server logs... Any help would be appreciated. Thank you!

**Comment by mendicm** [comment]
FYI: graphite is running on docker container and the metrics are collected every 10s

**Comment by GhostLyrics** [comment]
I'm not sure if this is a problem of this puppet module but I have the same issue for some metrics.

**Comment by mendicm** [comment]
Same problem on graphite-web:
<img width="1429" alt="captura de pantalla 2017-03-17 a las 19 50 16" src="https://cloud.githubusercontent.com/assets/4120546/24058319/fe53b2d0-0b4a-11e7-98a0-8a561a1cb5c7.png">

**Comment by GhostLyrics** [comment]
I am seeing the same thing even though I don't use this plugin. I'm using a plain TCP handler instead. I initially thought it might be due to the sample interval being too low, but you said you're sampling every 10 seconds?

**Comment by mendicm** [comment]
I'm using a tcp handler too but I posted the issue here because I don't know where to post it... And yes I'm sampling every 10s and downsampling throught graphite after 7 days of retention.

**Comment by mendicm** [comment]
Finally I found one of the client machines with the sensu-server service running, seems that the problem was this.
