### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by royjs** [sensu-plugins/sensu-plugins-graphite#49]
It has been a while since the last release. I'd like to be able to install the latest version of this plugin using sensu-install.

In particular, I need this commit: https://github.com/sensu-plugins/sensu-plugins-graphite/commit/cf81f6f32cea579930b1b29db97b2b5725bbc732 which is not part of 2.0.0

Is a new release planned soon?

**Comment by majormoses** [comment]
Apologies I am still trying to get more maintainers to release on merge.

released: https://rubygems.org/gems/sensu-plugins-graphite/versions/2.1.0
